### PR TITLE
Swap a global constant for a global function

### PR DESCRIPTION
**Pull request by szepeviktor**
@mallardduck Prisoner exchange for good.

### CODE REVIEW

**Comment by Gummibeer** [comment]
Should I add @szepeviktor to the repo? 😉

**Comment by szepeviktor** [comment]
> Should I add

Nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.

**Comment by szepeviktor** [comment]
Houston! [We've had a problem here.](https://www.youtube.com/watch?v=MdvoA-sjs0A)
`php_uname` returns `Windows NT`.

I'm quiet global constant-phobic. It makes me feel like PHP4/`GOTO`.

**Comment by Gummibeer** [comment]
@mallardduck should decide. I don't care about such details.

**Comment by szepeviktor** [comment]
@mallardduck Some inputs:

- https://en.wikipedia.org/wiki/Uname
- Cygwin:  `php_uname("s")` -> `CYGWIN_NT-10.0-19043`
- Cygwin: `echo PHP_OS_FAMILY;` -> `Unknown`
- windows.php.net uname -> Windows NT
- windows.php.net PHP_OS_FAMILY -> Windows
- there is also MSYS2

**Comment by szepeviktor** [comment]
`stripos('win', $uname)` won't work because of OSX's `Darwin`

I do not know your goal!
What's at stake here?
If only delimiter and separator then please use `DIRECTORY_SEPARATOR` and `PATH_SEPARATOR`
https://www.php.net/manual/en/dir.constants.php

...I see! https://nodejs.org/api/path.html#windows-vs-posix

**Comment by mallardduck** [comment]
I'm all for adding more folks if they're willing, but that doesn't seem the case lol.
TBH nothing is in `main` yet because nothing is ready for public scrutiny at this level.

If you want to be part of the problem solving at this early of a phase I would suggest you do accept @Gummibeer's offer. Since like I said, the more the merrier.

Ultimately I chose this constant because as of PHP 7.2 it's a new one that should be trustable to identify Windows OS family. Specifically it should identify PHP processes running on a Windows (family) OS via a Windows (execution mode) process. I.e. PHP compiled to run natively on Windows family OS (even if cross compiled from linux).

So I guess the fact that Cygwin's PHP doesn't identify as windows nor *nix isn't totally shocking. That's an edge case where a user is running PHP in a "true" hybrid mode. Where as a modern way to run *nix PHP on Windows might be WSL which AFAIK - last I checked - would identify as a *nix OS.

I raise this example because this is another "odd PHP runtime" example, however the OS this library target's (for that runtime) is much clearer as *nix under WSL.

At the end of the day - the Node.js module warns the same - the default `Path::{method}()` API will be slightly magic and attempt to detect the proper OS family the PHP runtime is currently in. If users need a consistent set of results (windows style vs *nix style) one way or the other, then they should explicitly work with that API.

I.e. In the node docs they say:
> To achieve consistent results when working with Windows file paths on any operating system, use [path.win32](https://nodejs.org/api/path.html#pathwin32):
and:
> To achieve consistent results when working with POSIX file paths on any operating system, use [path.posix](https://nodejs.org/api/path.html#pathposix):

Same rule could apply here, where someone should either append `::win32()` on the method chain, or `\Win32` on the namespace. Same would be true for Posix as well.

**Comment by mallardduck** [comment]
Ultimately, for me, since Windows is the "odd man out" as far as path style I'm not too worried about the "hybrid" runtimes that exist on Windows. Those hybrid models already generally exist as a bridge between Posix world and Windows.

So TBH I'm unsure how much I want us to do in the runtime side of things for versions of PHP on windows not specifically compiled to identify as windows. 🤔 

https://github.com/php/php-src/blob/ddc0b490f76b469591f851ccbce56c20ef93f333/main/php.h#L39-L52

**Comment by mallardduck** [comment]
Yeah, looking into it again - since it's been a decade since I touched Cygwin - since it's literally bringing POSIX environment and APIs into windows, we do not want it identified as windows. So as far as the concern about Cygwin getting POSIX behavior by default that would be "working as expected".

Given that MSYS2 says:
> all based on a modified version of [Cygwin](https://cygwin.com/)


I'm going to rule that the same category as a runtime that wants POSIX by default, so would be a non issue.

Were there any other use-case concerns you had that these replies don't cover @szepeviktor ?

**Review by mallardduck — COMMENTED** [review]
May not be needed - please see comments in main thread.

**Comment by szepeviktor** [comment]
> Were there any other use-case concerns

My fridge has Windows Mobile identifying itself as `FRIDGE_OS` 🤣

**Comment by szepeviktor** [comment]
> Should I add @szepeviktor to the repo? 😉

@Gummibeer OK! Please add me to this repo.

**Comment by mallardduck** [comment]
As far as this particular issue goes though, I think I clarified how the windows detection should work.
So in theory this can be closed?

**Comment by Gummibeer** [comment]
@szepeviktor is added to the repo https://github.com/Astrotomic/php-path/invitations

**Comment by szepeviktor** [comment]
Thank you Tom.
You get a mask, I get a bear!

**Pull request closed without merging**
